CREATE TABLE IF NOT EXISTS public.main_menu (
    id VARCHAR PRIMARY KEY,
    section VARCHAR,
    name VARCHAR,
    description VARCHAR,
    calories VARCHAR,
    fat VARCHAR,
    carbohydrates VARCHAR,
    protein VARCHAR,
    allergens VARCHAR,
    price REAL
);
INSERT INTO public.main_menu (id, section, name, description, calories, fat, carbohydrates, protein, allergens, price) VALUES
    ('tomato-bruschetta', 'starters', 'Tomato Bruschetta', 'Grilled bread topped with fresh tomatoes, garlic, and basil', '120 kcal', '4g', '18g', '4g', 'Gluten', 6),
    ('chicken-wings', 'starters', 'Chicken Wings', 'Spicy marinated chicken wings, served with blue cheese dip', '290 kcal', '18g', '5g', '22g', 'Dairy', 8),
    ('crispy-calamari', 'starters',  'Crispy Calamari', 'Lightly breaded calamari, fried and served with a side of marinara sauce', '310 kcal', '16g', '35g', '15g', 'Gluten, Shellfish', 9),
    ('beef-burger', 'mains', 'Beef Burger', 'Grass-fed beef patty with lettuce, tomato, and cheese, served on a brioche bun', '600 kcal', '30g', '40g', '40g', 'Gluten, Dairy', 12),
    ('vegetable-pasta', 'mains', 'Vegetable Pasta', 'Whole wheat pasta tossed with seasonal vegetables in a light tomato sauce', '420 kcal', '12g', '68g', '14g', 'Gluten', 11),
    ('grilled-salmon', 'mains', 'Grilled Salmon', 'Salmon fillet, grilled and served with a lemon dill sauce and steamed vegetables', '520 kcal', '28g', '20g', '50g', 'Fish', 15),
    ('quinoa-salad', 'mains', 'Quinoa Salad', 'A hearty salad with quinoa, mixed greens, avocados, tomatoes, cucumbers, and a lemon vinaigrette', '350 kcal', '14g', '45g', '12g', null, 10),
    ('craft-beer', 'alcoholic_drinks', 'Craft Beer', 'Locally brewed IPA with citrus and pine notes', '180 kcal', '0g', '14g', '2g', 'Gluten', 5),
    ('red-wine', 'alcoholic_drinks', 'Glass of Red Wine (125 ml)', 'Medium-bodied red wine with flavors of cherry and blackberry', '125 kcal', '0g', '4g', '0g', 'Sulfites', 7),
    ('white-wine', 'alcoholic_drinks', 'Glass of White Wine (125 ml)', 'Crisp and refreshing white wine with hints of apple and pear', '120 kcal', '0g', '3g', '0g', 'Sulfites', 7),
    ('lemonade', 'non_alcoholic_drinks', 'Lemonade', 'Freshly squeezed lemonade, sweetened with a touch of honey', '120 kcal', '0g', '32g', '0g', null, 3),
    ('iced-tea', 'non_alcoholic_drinks', 'Iced Tea', 'Cold-brewed black tea, served over ice with a lemon wedge', '90 kcal', '0g', '24g', '0g', null, 2.5),
    ('fruit-smoothie', 'non_alcoholic_drinks', 'Fruit Smoothie', 'A blend of seasonal fruits, yogurt, and honey', '200 kcal', '2g', '40g', '5g', 'Dairy', 4.5),
    ('sparkling-water', 'non_alcoholic_drinks', 'Sparkling Water (500 ml)', 'Naturally carbonated spring water with a choice of lemon or lime', '0 kcal', '0g', '0g', '0g', null, 2),
    ('tap-water', 'non_alcoholic_drinks', 'Tap Water (500 ml)', 'Regular tap water', '0 kcal', '0g', '0g', '0g', null, 0),
    ('coffee', 'hot_drinks', 'Coffee', 'Freshly brewed coffee from single-origin beans', '2 kcal', '0g', '0g', '0.3g', null, 2.5),
    ('green-tea', 'hot_drinks', 'Green Tea', 'Steamed green tea, known for its antioxidants', '0 kcal', '0g', '0g', '0g', null, 2),
    ('hot-chocolate', 'hot_drinks', 'Hot Chocolate', 'Rich and creamy hot chocolate, made with real cocoa and topped with whipped cream', '250 kcal', '12g', '32g', '8g', 'Dairy', 3),
    ('chocolate-lava-cake', 'desserts', 'Chocolate Lava Cake', 'Warm, gooey chocolate cake with a molten chocolate center, served with vanilla ice cream', '310 kcal', '18g', '34g', '4g', 'Gluten, Eggs, Dairy', 6),
    ('cheesecake', 'desserts', 'Cheesecake', 'Creamy cheesecake on a graham cracker crust, topped with fresh berries', '320 kcal', '20g', '26g', '6g', 'Gluten, Eggs, Dairy', 5.5),
    ('apple-pie', 'desserts', 'Apple Pie', 'Classic apple pie with a flaky crust, served with a scoop of vanilla ice cream', '350 kcal', '17g', '45g', '3g', 'Gluten, Dairy', 5);
